name: linux

on:
  - push

jobs:
  perl:
    runs-on: ubuntu-latest
    container:
      image: perl:5.34
    steps:
      - uses: actions/checkout@v1
      - name: carmel cache
        uses: actions/cache@v1
        with:
          path: .carmel
          key: ${{ runner.os }}-5.34-carmel-${{ hashFiles('cpanfile*') }}
      - name: Install
        run: ./script/install-carmel-cached
      - name: Verify
        run: ./script/verify-versions
