name: cpm-cached

on:
  - push

jobs:
  perl:
    runs-on: ubuntu-latest
    container:
      image: perl:5.34
    steps:
      - uses: actions/checkout@v1
      - name: cpm cache
        uses: actions/cache@v1
        with:
          path: .perl-cpm
          key: ${{ runner.os }}-5.34-cpm-v3-${{ hashFiles('cpanfile*', 'script/*cpm') }}
      - name: Install
        run: ./script/install-cpm
      - name: Verify
        run: ./script/verify-versions
