name: linux

on:
  - push

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - install-cpanm
          - install-carmel
          - install-carmel-cached
          - install-carton
          - install-cpm
          - install-cpm-cached
    container:
      image: perl:5.34
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: ./script/${{ matrix.script }}
      - name: Verify
        run: ./script/verify-versions
